### ISSUE TITLE
Placing in /etc/profile.d breaks X

### ISSUE THREAD

**Issue by plasmoduck** [gagle/raspberrypi-motd#13]
After copying scipt to /etc/profile.d and rebooting. The graphical login screen is stuck in an endless loop asking for password, I input correct password then it loops back to asking for password again. Removing the file from /etc/profile.d and rebooting fixed this and allowed me to login and start the desktop.

**Comment by P4N1CO** [comment]
I have the same problem, and when running cat .xsession-errors the error "/ etc / X11 / Xsession: 5: /etc/profile.d/motd.sh: Syntax error:" ("unexpected"

**Comment by plasmoduck** [comment]
Here is my forked version with correct way to install
https://plasmoduck.github.io/raspberrypi-motd/

**Comment by plasmoduck** [comment]
Source the motd.sh script in the file ~/.profile by placing a link to 
it at the end of the file like /path/to/motd.sh and it will be executed 
after login.

**Comment by P4N1CO** [comment]
Very good, it worked.
